# Generated by Django 2.2.7 on 2022-11-02 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAgentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('verify', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('isPayed', models.BooleanField(default=False)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('leadUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleslead_Lead_user', to=settings.AUTH_USER_MODEL)),
                ('orgUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleslead_Org_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
