# Generated by Django 2.2.7 on 2022-09-08 10:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aboutevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gst', models.FileField(max_length=255, upload_to='image/events/company/gst')),
                ('contact_no', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('flat_no', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventimage',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='area_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='flat_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventvideo',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='location_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='pincode',
            field=models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(999999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='state',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventPersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('is_mobile_hidden', models.BooleanField(default=False)),
                ('alt_mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('is_alt_mobile_hidden', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=100)),
                ('is_email_hidden', models.BooleanField(default=True)),
                ('flat_no', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EventRegistration')),
            ],
        ),
        migrations.CreateModel(
            name='EventCompanyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(blank=True, null=True, upload_to='image/events/company/video')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='api.EventCompanyDetails')),
            ],
        ),
        migrations.CreateModel(
            name='EventCompanyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/events/company')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='api.EventCompanyDetails')),
            ],
        ),
        migrations.AddField(
            model_name='eventcompanydetails',
            name='event_reg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EventRegistration'),
        ),
    ]
