# Generated by Django 2.2.7 on 2022-09-23 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220923_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgequipment',
            old_name='orgequipment',
            new_name='orgequipmentdiscounts',
        ),
        migrations.AddField(
            model_name='orgequipment',
            name='orgequipment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgequipment', to='api.SeatingArrangementBooking'),
        ),
    ]
