# Generated by Django 2.2.7 on 2022-09-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220923_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgequipment',
            name='orgequipmentdiscounts',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
