# Generated by Django 2.2.7 on 2022-09-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220927_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetEvent',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='about_event',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='discount_type',
            field=models.CharField(choices=[('discount_on_total_bill', 'Discount On Total Bill'), ('discount_on_equipment_or_item', 'Discount On Equipment Or Item'), ('advance_and_discount_confirmation', 'Advance And Discount Confirmation')], max_length=50),
        ),
    ]
