# Generated by Django 2.2.7 on 2022-09-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('country_code', models.CharField(max_length=6)),
                ('role', models.CharField(choices=[(0, 'superadmin'), (1, 'admin'), (2, 'subadmin'), (3, 'executive'), (4, 'organizer'), (5, 'user')], default=5, max_length=250)),
                ('about', models.TextField(blank=True, null=True)),
                ('admin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('verify', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('refer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('my_refer_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtpLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('smsKey', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
