# Generated by Django 2.2.7 on 2022-09-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(0, 'superadmin'), (1, 'admin'), (2, 'subadmin'), (3, 'executive'), (4, 'organizer'), (5, 'user')], default=5, max_length=250),
        ),
    ]
