# Generated by Django 2.2.7 on 2022-09-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otplog',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
