# Generated by Django 2.2.7 on 2022-10-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otplog_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(blank=True, default='media/image/profile/default.jpg', null=True, upload_to='media/image/profile/'),
        ),
    ]
